sudo: false

notifications:
  email: false

language: node_js

node_js:
  - "10"

cache:
  directories:
    - node_modules

services:
  - xvfb

install:
  - npm install

addons:
  sauce_connect: true

script:
  - npm run build
  - COVERAGE=true npm run test

after_success: npm run size